CREATE TABLE customers (
  id uuid NOT NULL PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  birth_place VARCHAR(255) NOT NULL,
  birth_date DATE NOT NULL,
  phone_number VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  pin TEXT NOT NULL,
  national_id TEXT NOT NULL,
  is_employeed BOOLEAN NOT NULL,
  job VARCHAR(255),
  mother_name VARCHAR(255) NOT NULL,
  is_verified BOOLEAN NOT NULL,
  address VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);